#############################################################################
# Makefile for building: model
# Generated by qmake (3.0) (Qt 5.1.1) on: ?? ?? 16 11:14:45 2014
# Project:  model.pro
# Template: subdirs
# Command: d:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\bin\qmake.exe -o Makefile model.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = d:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: model.pro D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\win32-msvc2012\qmake.conf D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\spec_pre.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\common\shell-win32.conf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\qconfig.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axbase.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axserver.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_clucene.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_concurrent.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_core.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_dbus.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_declarative.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_designer.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_ftp.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_gui.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_help.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_multimedia.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_network.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_opengl.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_printsupport.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qml.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qmltest.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_quick.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_script.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_scripttools.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_sensors.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_serialport.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_sql.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_svg.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_testlib.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_uitools.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_v8.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_webkit.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_widgets.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_xml.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\qt_functions.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\qt_config.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\win32-msvc2012\qmake.conf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\spec_post.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\exclusive_builds.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\default_pre.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\default_pre.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\resolve_config.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\default_post.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\rtti.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\warn_on.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\windows.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\testcase_targets.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\exceptions.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\yacc.prf \
		D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\lex.prf \
		model.pro
	$(QMAKE) -o Makefile model.pro
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\spec_pre.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\common\shell-win32.conf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\qconfig.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axbase.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_axserver.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_clucene.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_concurrent.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_core.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_datavisualization.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_dbus.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_declarative.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_designer.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_ftp.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_gui.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_help.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_multimedia.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_network.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_opengl.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_printsupport.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qml.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qmltest.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_quick.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_script.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_scripttools.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_sensors.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_serialport.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_sql.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_svg.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_testlib.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_uitools.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_v8.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_webkit.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_widgets.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_xml.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\qt_functions.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\qt_config.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\win32-msvc2012\qmake.conf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\spec_post.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\exclusive_builds.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\default_pre.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\default_pre.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\resolve_config.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\default_post.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\rtti.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\warn_on.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\win32\windows.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\testcase_targets.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\exceptions.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\yacc.prf:
D:\IDE\Qt\Qt5.1.1\5.1.1\msvc2012\mkspecs\features\lex.prf:
model.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile model.pro

qmake_all: sub-src-qmake_all FORCE

make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-sub_Debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-sub_Debug

sub-src-sub_Release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-sub_Release

sub-src-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Workspace\cpp\design-patterns\src\src.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

