######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 17:11:30 2012
######################################################################

TEMPLATE = app
TARGET = a
DEPENDPATH += .
INCLUDEPATH += . \
               ../include

CONFIG -= qt
CONFIG += debug console

DESTDIR = ../bin

# Input
HEADERS += heads.h
SOURCES += assembly.cpp
